### ISSUE TITLE
Move echarts to kindly from clay

### ISSUE THREAD

**Issue by dmg46664** [scicloj/kindly#1]
I presume that the following defined in `clay` project should be moved to `kindly`.
https://github.com/scicloj/clay/blob/main/src/scicloj/clay/v1/tool/clerk.clj#L155

Otherwise, if clay breaks for unrelated reasons, then this functionality breaks too.
I don't understand why this project doesn't have clerk specific stuff where as `clay` does....

**Comment by daslu** [comment]
@dmg46664 thanks, it is a good idea to rethink the division of roles between these two libraries.

Possibly you are right about this, let us discuss soon.

**Comment by daslu** [comment]
This is fixed in the current Kindly v4 / Clay v2 settings.
Thanks, @dmg46664.
